#ifndef __LITE_BEAPI_INTERFACE_DEFS_H__
#define __LITE_BEAPI_INTERFACE_DEFS_H__

#include <be/interface/GraphicsDefs.h>

#define border_style			e_border_style
#define B_PLAIN_BORDER			E_PLAIN_BORDER
#define B_FANCY_BORDER			E_FANCY_BORDER
#define B_NO_BORDER			E_NO_BORDER

#define orientation			e_orientation
#define B_HORIZONTAL			E_HORIZONTAL
#define B_VERTICAL			E_VERTICAL

#define B_SHIFT_KEY			E_SHIFT_KEY
#define B_COMMAND_KEY			E_COMMAND_KEY
#define B_CONTROL_KEY			E_CONTROL_KEY
#define B_CAPS_LOCK			E_CAPS_LOCK
#define B_SCROLL_LOCK			E_SCROLL_LOCK
#define B_NUM_LOCK			E_NUM_LOCK
#define B_OPTION_KEY			E_OPTION_KEY
#define B_MENU_KEY			E_MENU_KEY
#define B_LEFT_SHIFT_KEY		E_LEFT_SHIFT_KEY
#define B_RIGHT_SHIFT_KEY		E_RIGHT_SHIFT_KEY
#define B_LEFT_COMMAND_KEY		E_LEFT_COMMAND_KEY
#define B_RIGHT_COMMAND_KEY		E_RIGHT_COMMAND_KEY
#define B_LEFT_CONTROL_KEY		E_LEFT_CONTROL_KEY
#define B_RIGHT_CONTROL_KEY		E_RIGHT_CONTROL_KEY
#define B_LEFT_OPTION_KEY		E_LEFT_OPTION_KEY
#define B_RIGHT_OPTION_KEY		E_RIGHT_OPTION_KEY

#endif /* __LITE_BEAPI_INTERFACE_DEFS_H__ */

