#include <be/interface/InterfaceDefs.h>
#include <be/interface/Rect.h>
#include <be/app/Handler.h>

#ifndef __LITE_BEAPI_VIEW_H__
#define __LITE_BEAPI_VIEW_H__

#ifdef __cplusplus

// class
#define BView				EView

#endif /* __cplusplus */

/* others */
#define B_PRIMARY_MOUSE_BUTTON		E_PRIMARY_MOUSE_BUTTON
#define B_SECONDARY_MOUSE_BUTTON	E_SECONDARY_MOUSE_BUTTON
#define B_TERTIARY_MOUSE_BUTTON		E_TERTIARY_MOUSE_BUTTON

#define B_ENTERED_VIEW			E_ENTERED_VIEW
#define B_INSIDE_VIEW			E_INSIDE_VIEW
#define B_EXITED_VIEW			E_EXITED_VIEW
#define B_OUTSIDE_VIEW			E_OUTSIDE_VIEW

#define B_POINTER_EVENTS		E_POINTER_EVENTS
#define B_SUSPEND_VIEW_FOCUS		E_SUSPEND_VIEW_FOCUS
#define B_NO_POINTER_HISTORY		E_NO_POINTER_HISTORY

#define B_FONT_FAMILY_AND_STYLE		E_FONT_FAMILY_AND_STYLE
#define B_FONT_SIZE			E_FONT_SIZE
#define B_FONT_SHEAR			E_FONT_SHEAR
#define B_FONT_SPACING			E_FONT_SPACING
#define B_FONT_ALL			E_FONT_ALL
#define B_FONT_ROTATION			0
#define B_FONT_ENCODING			0
#define B_FONT_FACE			0
#define B_FONT_FLAGS			0

#define B_WILL_DRAW			E_WILL_DRAW
#define B_PULSE_NEEDED			E_PULSE_NEEDED
#define B_NAVIGABLE			E_NAVIGABLE
#define B_NAVIGABLE_JUMP		E_NAVIGABLE_JUMP
#define B_FRAME_EVENTS			E_FRAME_EVENTS
#define B_DRAW_ON_CHILDREN		E_DRAW_ON_CHILDREN
#define B_INPUT_METHOD_AWARE		E_INPUT_METHOD_AWARE
#define B_FULL_UPDATE_ON_RESIZE		0
#define B_SUBPIXEL_PRECISE		0

#define B_FOLLOW_NONE			E_FOLLOW_NONE
#define B_FOLLOW_ALL			E_FOLLOW_ALL
#define B_FOLLOW_ALL_SIDES		E_FOLLOW_ALL
#define B_FOLLOW_LEFT			E_FOLLOW_LEFT
#define B_FOLLOW_RIGHT			E_FOLLOW_RIGHT
#define B_FOLLOW_LEFT_RIGHT		E_FOLLOW_LEFT_RIGHT
#define B_FOLLOW_H_CENTER		E_FOLLOW_H_CENTER
#define B_FOLLOW_TOP			E_FOLLOW_TOP
#define B_FOLLOW_BOTTOM			E_FOLLOW_BOTTOM
#define B_FOLLOW_TOP_BOTTOM		E_FOLLOW_TOP_BOTTOM
#define B_FOLLOW_V_CENTER		E_FOLLOW_V_CENTER

#endif /* __LITE_BEAPI_VIEW_H__ */

