#include <be/interface/View.h>

#ifndef __LITE_BEAPI_WINDOW_H__
#define __LITE_BEAPI_WINDOW_H__

#ifdef __cplusplus

// class
#define BWindow				EWindow

#endif /* __cplusplus */

/* others */
#define window_type			e_window_type
#define B_UNTYPED_WINDOW		E_UNTYPED_WINDOW
#define B_TITLED_WINDOW			E_TITLED_WINDOW
#define B_MODAL_WINDOW			E_MODAL_WINDOW
#define B_DOCUMENT_WINDOW		E_DOCUMENT_WINDOW
#define B_BORDERED_WINDOW		E_BORDERED_WINDOW
#define B_FLOATING_WINDOW		E_FLOATING_WINDOW

#define window_look			e_window_look
#define B_BORDERED_WINDOW_LOOK		E_BORDERED_WINDOW_LOOK
#define B_NO_BORDER_WINDOW_LOOK		E_NO_BORDER_WINDOW_LOOK
#define B_TITLED_WINDOW_LOOK		E_TITLED_WINDOW_LOOK
#define B_DOCUMENT_WINDOW_LOOK		E_DOCUMENT_WINDOW_LOOK
#define B_MODAL_WINDOW_LOOK		E_MODAL_WINDOW_LOOK
#define B_FLOATING_WINDOW_LOOK		E_FLOATING_WINDOW_LOOK

#define window_feel			e_window_feel
#define B_NORMAL_WINDOW_FEEL		E_NORMAL_WINDOW_FEEL
#define B_MODAL_SUBSET_WINDOW_FEEL	E_MODAL_SUBSET_WINDOW_FEEL
#define B_MODAL_APP_WINDOW_FEEL		E_MODAL_APP_WINDOW_FEEL
#define B_MODAL_ALL_WINDOW_FEEL		E_MODAL_ALL_WINDOW_FEEL
#define B_FLOATING_SUBSET_WINDOW_FEEL	E_FLOATING_SUBSET_WINDOW_FEEL
#define B_FLOATING_APP_WINDOW_FEEL	E_FLOATING_APP_WINDOW_FEEL
#define B_FLOATING_ALL_WINDOW_FEEL	E_FLOATING_ALL_WINDOW_FEEL

#define B_NOT_MOVABLE			E_NOT_MOVABLE
#define B_NOT_CLOSABLE			E_NOT_CLOSABLE
#define B_NOT_ZOOMABLE			E_NOT_ZOOMABLE
#define B_NOT_MINIMIZABLE		E_NOT_MINIMIZABLE
#define B_NOT_RESIZABLE			E_NOT_RESIZABLE
#define B_NOT_H_RESIZABLE		E_NOT_H_RESIZABLE
#define B_NOT_V_RESIZABLE		E_NOT_V_RESIZABLE
#define B_AVOID_FRONT			E_AVOID_FRONT
#define B_AVOID_FOCUS			E_AVOID_FOCUS
#define B_WILL_ACCEPT_FIRST_CLICK	E_WILL_ACCEPT_FIRST_CLICK
#define B_OUTLINE_RESIZE		E_OUTLINE_RESIZE
#define B_NO_WORKSPACE_ACTIVATION	E_NO_WORKSPACE_ACTIVATION
#define B_NOT_ANCHORED_ON_ACTIVATE	E_NOT_ANCHORED_ON_ACTIVATE
#define B_ASYNCHRONOUS_CONTROLS		0
#define B_QUIT_ON_WINDOW_CLOSE		E_QUIT_ON_WINDOW_CLOSE

#define B_CURRENT_WORKSPACE		E_CURRENT_WORKSPACE
#define B_ALL_WORKSPACES		E_ALL_WORKSPACES

#endif /* __LITE_BEAPI_WINDOW_H__ */

